language: groovy
sudo: false
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- export TZ=Australia/Canberra
- date
- rm -rf ~/.sdkman
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- "~/install_gvm.sh"
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION:$GRAILS_VERSION"
- sdk install grails $GRAILS_VERSION || true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install karma
- npm install karma-jasmine
- npm install karma-coverage
- npm install karma-ng-html2js-preprocessor --save-dev
- npm install karma-phantomjs-launcher
- npm install karma-chrome-launcher --save-dev
- npm install karma-firefox-launcher --save-dev
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_grails_settings_new.groovy
- MAVEN_REPO="ala-repo-snapshot"; grep '^app\.version=' ./application.properties |
  grep -q "\-SNAPSHOT"; if [ "$?" = "1" ]; then MAVEN_REPO="ala-repo-release"; fi;
- echo "MAVEN_REPO:$MAVEN_REPO"
script:
- node_modules/karma/bin/karma start karma.conf.js --single-run --browsers Firefox,PhantomJS
- grails clean && grails refresh-dependencies --non-interactive && grails test-app --non-interactive && grails prod war --non-interactive && grails prod maven-deploy --repository=$MAVEN_REPO --non-interactive --stacktrace
env:
  global:
  - secure: HQaT+1B5r/7A15V3QHs5Lw1S8jNWgjgCKa8Fz7aEF4F+FHBiTqqM/fvFWcC+g7KHkLhgTht2efEIp9akBt8sArz1xp/BGhKr4JJRGU2uYJE8NpFb08u1OPAvurWQ72bwihJQBJWI9VXiQGoGQffLQL1yLQmlGMFbU/sOLzUxhGQ=
  - secure: Dc3FdXwu0j+tKyETSmZmULlEmVpQ7yKk+74zauRfEts0IyH1gUEuFr2ODTNUUFrjNRR/yW2dc0erlCyUc/CAGdALVRFzImz45WUjs0VgBtH2MW6tkgLd4DhDTDUpxOZMKZBEK91UVqK/2C0811c3UbvDBbuGrNacW5PPdzYoS9o=
